service: chi-data

provider:
  name: aws
  runtime: python2.7
  timeout: 300

functions:
  articles:
    handler: articles.handler
    events:
        - schedule: 'rate(10 minutes)'
  chicago:
    handler: chicago.handler
    events:
        - schedule: 'rate(24 hours)'